all: Floyd Dijkstra

Floyd: Floyd.cc Graph_Matrix.cc Graph_Matrix.h
	g++ Floyd.cc Graph_Matrix.cc Graph_Matrix.h -o Floyd -g

Dijkstra: Dijkstra.cc Graph_Matrix.cc Graph_Matrix.h
	g++ Dijkstra.cc Graph_Matrix.cc Graph_Matrix.h -o Dijkstra -g

clean:
	rm -f Floyd

